/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SvLink {
    'href': string;
    'target': string;
  }
  interface SvPicture {
    'alt': string;
    'src': string;
    'srcset': string;
  }
}

declare global {


  interface HTMLSvLinkElement extends Components.SvLink, HTMLStencilElement {}
  var HTMLSvLinkElement: {
    prototype: HTMLSvLinkElement;
    new (): HTMLSvLinkElement;
  };

  interface HTMLSvPictureElement extends Components.SvPicture, HTMLStencilElement {}
  var HTMLSvPictureElement: {
    prototype: HTMLSvPictureElement;
    new (): HTMLSvPictureElement;
  };
  interface HTMLElementTagNameMap {
    'sv-link': HTMLSvLinkElement;
    'sv-picture': HTMLSvPictureElement;
  }
}

declare namespace LocalJSX {
  interface SvLink extends JSXBase.HTMLAttributes<HTMLSvLinkElement> {
    'href'?: string;
    'target'?: string;
  }
  interface SvPicture extends JSXBase.HTMLAttributes<HTMLSvPictureElement> {
    'alt'?: string;
    'src'?: string;
    'srcset'?: string;
  }

  interface IntrinsicElements {
    'sv-link': SvLink;
    'sv-picture': SvPicture;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


